# Generated by Django 4.1.4 on 2023-07-21 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drugFinder', '0009_alter_prescription_sentdate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subcity', models.CharField(max_length=100)),
                ('kebele', models.CharField(max_length=100)),
                ('houseNo', models.CharField(max_length=50)),
                ('phoneNo', models.CharField(max_length=20)),
                ('loc_latitude', models.DecimalField(decimal_places=15, max_digits=18)),
                ('loc_longitude', models.DecimalField(decimal_places=15, max_digits=18)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('payMethod', models.CharField(max_length=20)),
                ('paid', models.BooleanField(default=False)),
                ('recieved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prescriptionImage', models.ImageField(null=True, upload_to='documents/')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugOrder.address')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugFinder.drugs')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugFinder.pharmacy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugFinder.drugs')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugFinder.pharmacy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
