# Generated by Django 4.1.4 on 2023-08-01 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drugFinder', '0013_pharmarating_customer_name'),
        ('drugOrder', '0002_order_assigneddeliverer_order_validprescription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='drugFinder.drugs'),
        ),
        migrations.AlterField(
            model_name='order',
            name='drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='drugFinder.drugs'),
        ),
    ]
