# Generated by Django 4.1.4 on 2023-05-16 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('image', models.ImageField(upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='Feedbacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senderName', models.CharField(max_length=100)),
                ('sentDate', models.DateField()),
                ('pharmacyName', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, null=True)),
                ('OwnersFname', models.CharField(max_length=50, null=True)),
                ('ownersLname', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('phoneNo', models.CharField(max_length=14, null=True)),
                ('licenseNo', models.CharField(max_length=30, null=True)),
                ('subCity', models.CharField(max_length=100, null=True)),
                ('kebele', models.CharField(max_length=100, null=True)),
                ('houseNo', models.CharField(max_length=30, null=True)),
                ('approved', models.BooleanField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugFinder.document')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugFinder.location')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senderName', models.CharField(max_length=100)),
                ('drugName', models.CharField(max_length=100)),
                ('sentDate', models.DateField()),
                ('getResponse', models.BooleanField()),
                ('prescriptionImage', models.ImageField(upload_to='documents/')),
                ('user', models.CharField(max_length=100)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='drugFinder.pharmacy')),
            ],
        ),
        migrations.CreateModel(
            name='Drugs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DrugName', models.CharField(max_length=100)),
                ('BrandName', models.CharField(max_length=50)),
                ('GenericName', models.CharField(max_length=50)),
                ('BatchNo', models.CharField(max_length=50)),
                ('Dosage', models.CharField(max_length=100)),
                ('Manufacturer', models.CharField(max_length=200)),
                ('Price', models.IntegerField()),
                ('Strength', models.CharField(max_length=20)),
                ('ExpireDate', models.DateField()),
                ('ManufacturedDate', models.DateField()),
                ('Quantity', models.IntegerField()),
                ('additional', models.CharField(max_length=300)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='drugFinder.pharmacy')),
            ],
        ),
    ]
