# Generated by Django 4.1.4 on 2023-05-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugFinder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
