# Generated by Django 4.1.4 on 2023-05-22 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugFinder', '0002_prescription_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(decimal_places=15, max_digits=18),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(decimal_places=15, max_digits=18),
        ),
    ]
