# Generated by Django 4.1.4 on 2023-05-23 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drugFinder', '0003_alter_location_latitude_alter_location_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugs',
            name='pharmacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugFinder.pharmacy'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='pharmacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugFinder.pharmacy'),
        ),
    ]
