# Generated by Django 4.1.4 on 2023-05-24 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drugFinder', '0004_alter_drugs_pharmacy_alter_prescription_pharmacy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbacks',
            name='pharmacyName',
        ),
        migrations.CreateModel(
            name='PharmaRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('rating', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugFinder.pharmacy')),
            ],
        ),
    ]
