# Generated by Django 4.1.4 on 2023-05-24 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugFinder', '0005_remove_feedbacks_pharmacyname_pharmarating'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacks',
            name='pharmacyName',
            field=models.CharField(default=True, max_length=150),
        ),
    ]
