# Generated by Django 4.1.4 on 2023-05-29 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugFinder', '0006_feedbacks_pharmacyname'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugs',
            name='Category',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
