# Generated by Django 4.1.4 on 2023-07-17 12:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('drugFinder', '0007_drugs_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbacks',
            name='sentDate',
        ),
        migrations.AddField(
            model_name='feedbacks',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedbacks',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
