# Generated by Django 4.1.4 on 2023-07-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugFinder', '0008_remove_feedbacks_sentdate_feedbacks_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='sentDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
