# Generated by Django 4.1.4 on 2023-07-26 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugFinder', '0009_alter_prescription_sentdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='prescriptionImage',
        ),
    ]
