# Generated by Django 4.1.4 on 2023-07-26 12:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('drugFinder', '0010_remove_prescription_prescriptionimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='prescriptionImage',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='documents/'),
            preserve_default=False,
        ),
    ]
