# Generated by Django 4.1.4 on 2023-07-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugFinder', '0011_prescription_prescriptionimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='prescriptionImage',
            field=models.ImageField(upload_to='prescriptions/'),
        ),
    ]
