# Generated by Django 4.1.4 on 2023-08-02 15:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('drugFinder', '0013_pharmarating_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='validDocument',
            field=models.BooleanField(default=False),
        ),
    ]
