# Generated by Django 4.1.4 on 2023-05-09 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pharmacy_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
