# Generated by Django 4.1.4 on 2023-08-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_PasswordChanged',
            field=models.BooleanField(default=True),
        ),
    ]
